ITEM.name = "12g Dragon's Breath"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "12 Gauge -DB-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.price = 650
ITEM.description= "A box that contains %s 12 gauge shells. "
ITEM.longdesc = "Standard 12 gauge shell filled with 6 mm shot. Highly lethal at close range. Only suitable for use with smoothbore weapons."
ITEM.flag = "1"
ITEM.img = Material("vgui/hud/12gauge.png")
ITEM.weight = 0.6
ITEM.isAmmo = true