ITEM.name = "12g Buckshot"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.ammo = "12 Gauge" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.price = 600
ITEM.description= "A box that contains %s 12 gauge shells. "
ITEM.longdesc = "Standard 12 gauge shell filled with 6 mm shot. Highly lethal at close range. Only suitable for use with smoothbore weapons."
ITEM.flag = "1"
ITEM.weight = 0.45
ITEM.img = Material("stalker2/ui/ammunition/ammo_12x70_buck.png")