ITEM.name = "12g Slug"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.ammo = "12 Gauge -SG-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s 12 gauge slug shells. "
ITEM.longdesc = "This heavy 12-caliber slug round is normally used for hunting big game, but is also good for other purposes."
ITEM.price = 1600
ITEM.flag = "2"
ITEM.Range = 20
ITEM.Dmg = 1
ITEM.Pen = 5
ITEM.weight = 0.5
ITEM.img = Material("stalker2/ui/ammunition/ammo_12x70_slug.png")