ITEM.name = "20g Slug"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.ammo = "20 Gauge -SG-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s 20 gauge slug shells. "
ITEM.longdesc = "This heavy 20-caliber slug round is normally used for hunting big game, but is also good for other purposes."
ITEM.price = 500
ITEM.flag = "2"
ITEM.Range = 20
ITEM.Dmg = 1
ITEM.Pen = 5
ITEM.weight = 0.5
ITEM.img = Material("stalkerAnomaly/mods/Maids_Vanilla_HD_icons/ui/ammunition/ammo_20x70.png")