ITEM.name = "7.62x54mm Belt Armor-Piercing"
ITEM.model = "models/kek1ch/ammo_pkm.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x54MMB -AP-"
ITEM.description = "A belt that contains %s rounds of 7.62x54mmR."
ITEM.category = "Ammunition"
ITEM.price = 30000
ITEM.flag = "4"
ITEM.ammoAmount = 100
ITEM.weight = 6
ITEM.isAmmo = true